FROM mcr.microsoft.com/dotnet/sdk:8.0 as api-ven

WORKDIR /app

COPY /TarGest .

WORKDIR /TarGest/TarGest.API

RUN dotnet publish -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app

COPY --from=ap-ven /api/out . 
ENTRYPOINT [ "dotnet" ,"TarGest.API.dll"]