// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TarGest.API.Conexao;

#nullable disable

namespace TarGest.API.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260526234157_migracaoV2")]
    partial class migracaoV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TarGest.API.Entidades.Tarefa", b =>
                {
                    b.Property<int>("tarefaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tarefaId"));

                    b.Property<string>("descricaoTarefa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("estadoTarefa")
                        .HasColumnType("int");

                    b.Property<DateTime>("horaInicioTarefa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("prazoTarefa")
                        .HasColumnType("datetime2");

                    b.Property<string>("tituloTarefa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tarefaId");

                    b.ToTable("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
